# Helpful head start from https://github.com/SanderKnape/cognito-apigateway-jwt
#
# aws cloudformation create-stack --stack-name "janker" --template-body file://simple-cfn.yml
# aws cloudformation update-stack --stack-name "janker" --template-body file://simple-cfn.yml
# aws cloudformation delete-stack --stack-name janker
AWSTemplateFormatVersion: 2010-09-09
Description: Al's Sample Template

Resources:

  JankerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: janker-log
      RetentionInDays: 3

  JankerApiV2:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Name: janker
      ProtocolType: HTTP

  JankerGetRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      RouteKey: GET /{stinky}/mofo/{greed+}
      ApiId: !Ref JankerApiV2
      # Can't find this integrations/ thing in any doc, but stack create
      # fails with an error that says it's required.
      Target: !Sub "integrations/${JankerGetIntegration}"

  JankerGetIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref JankerApiV2
      IntegrationType: HTTP_PROXY
      IntegrationMethod: GET
      IntegrationUri: http://httpbin.org/anything
      RequestParameters:
        # Only one per integration? This works.
        {"remove:querystring.val":"''", 
         "remove:querystring.key":"''",
         "remove:querystring.butt":"", 
         "remove:querystring.wipe":"",
         "overwrite:path":"anything/${request.path}"}
      PayloadFormatVersion: 1.0

  # aws logs tail janker-log
  JankerStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: $default
      ApiId: !Ref JankerApiV2
      AutoDeploy: true
      AccessLogSettings:
        DestinationArn: !GetAtt JankerLogGroup.Arn
        Format: 'requestId: $context.requestId
          integrationLatency: $context.integrationLatency
          responseLatency: $context.responseLatency
          httpMethod: $context.httpMethod
          routeKey: $context.routeKey
          path: $context.path'